// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/port/cache_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/port/cache_repository.go -destination=internal/app/port/mock/mock_cache_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	message "github.com/yanosea/gosl/internal/domain/message"
	gomock "go.uber.org/mock/gomock"
)

// MockCacheRepository is a mock of CacheRepository interface.
type MockCacheRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCacheRepositoryMockRecorder
	isgomock struct{}
}

// MockCacheRepositoryMockRecorder is the mock recorder for MockCacheRepository.
type MockCacheRepositoryMockRecorder struct {
	mock *MockCacheRepository
}

// NewMockCacheRepository creates a new mock instance.
func NewMockCacheRepository(ctrl *gomock.Controller) *MockCacheRepository {
	mock := &MockCacheRepository{ctrl: ctrl}
	mock.recorder = &MockCacheRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheRepository) EXPECT() *MockCacheRepositoryMockRecorder {
	return m.recorder
}

// EstimateMemoryUsage mocks base method.
func (m *MockCacheRepository) EstimateMemoryUsage() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EstimateMemoryUsage")
	ret0, _ := ret[0].(int64)
	return ret0
}

// EstimateMemoryUsage indicates an expected call of EstimateMemoryUsage.
func (mr *MockCacheRepositoryMockRecorder) EstimateMemoryUsage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EstimateMemoryUsage", reflect.TypeOf((*MockCacheRepository)(nil).EstimateMemoryUsage))
}

// GetCurrentChannel mocks base method.
func (m *MockCacheRepository) GetCurrentChannel() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentChannel")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetCurrentChannel indicates an expected call of GetCurrentChannel.
func (mr *MockCacheRepositoryMockRecorder) GetCurrentChannel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentChannel", reflect.TypeOf((*MockCacheRepository)(nil).GetCurrentChannel))
}

// GetMessages mocks base method.
func (m *MockCacheRepository) GetMessages(channelID string) ([]message.Message, string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessages", channelID)
	ret0, _ := ret[0].([]message.Message)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(bool)
	return ret0, ret1, ret2
}

// GetMessages indicates an expected call of GetMessages.
func (mr *MockCacheRepositoryMockRecorder) GetMessages(channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessages", reflect.TypeOf((*MockCacheRepository)(nil).GetMessages), channelID)
}

// SetCurrentChannel mocks base method.
func (m *MockCacheRepository) SetCurrentChannel(channelID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCurrentChannel", channelID)
}

// SetCurrentChannel indicates an expected call of SetCurrentChannel.
func (mr *MockCacheRepositoryMockRecorder) SetCurrentChannel(channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCurrentChannel", reflect.TypeOf((*MockCacheRepository)(nil).SetCurrentChannel), channelID)
}

// StoreMessages mocks base method.
func (m *MockCacheRepository) StoreMessages(channelID string, msgs []message.Message, cursor string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StoreMessages", channelID, msgs, cursor)
}

// StoreMessages indicates an expected call of StoreMessages.
func (mr *MockCacheRepositoryMockRecorder) StoreMessages(channelID, msgs, cursor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreMessages", reflect.TypeOf((*MockCacheRepository)(nil).StoreMessages), channelID, msgs, cursor)
}
