// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/port/slack_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/port/slack_repository.go -destination=internal/app/port/mock/mock_slack_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	port "github.com/yanosea/gosl/internal/app/port"
	channel "github.com/yanosea/gosl/internal/domain/channel"
	message "github.com/yanosea/gosl/internal/domain/message"
	user "github.com/yanosea/gosl/internal/domain/user"
	gomock "go.uber.org/mock/gomock"
)

// MockSlackEvent is a mock of SlackEvent interface.
type MockSlackEvent struct {
	ctrl     *gomock.Controller
	recorder *MockSlackEventMockRecorder
	isgomock struct{}
}

// MockSlackEventMockRecorder is the mock recorder for MockSlackEvent.
type MockSlackEventMockRecorder struct {
	mock *MockSlackEvent
}

// NewMockSlackEvent creates a new mock instance.
func NewMockSlackEvent(ctrl *gomock.Controller) *MockSlackEvent {
	mock := &MockSlackEvent{ctrl: ctrl}
	mock.recorder = &MockSlackEventMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSlackEvent) EXPECT() *MockSlackEventMockRecorder {
	return m.recorder
}

// SlackEvent mocks base method.
func (m *MockSlackEvent) SlackEvent() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SlackEvent")
}

// SlackEvent indicates an expected call of SlackEvent.
func (mr *MockSlackEventMockRecorder) SlackEvent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SlackEvent", reflect.TypeOf((*MockSlackEvent)(nil).SlackEvent))
}

// MockSlackRepository is a mock of SlackRepository interface.
type MockSlackRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSlackRepositoryMockRecorder
	isgomock struct{}
}

// MockSlackRepositoryMockRecorder is the mock recorder for MockSlackRepository.
type MockSlackRepositoryMockRecorder struct {
	mock *MockSlackRepository
}

// NewMockSlackRepository creates a new mock instance.
func NewMockSlackRepository(ctrl *gomock.Controller) *MockSlackRepository {
	mock := &MockSlackRepository{ctrl: ctrl}
	mock.recorder = &MockSlackRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSlackRepository) EXPECT() *MockSlackRepositoryMockRecorder {
	return m.recorder
}

// Connect mocks base method.
func (m *MockSlackRepository) Connect(ctx context.Context, botToken, appToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect", ctx, botToken, appToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// Connect indicates an expected call of Connect.
func (mr *MockSlackRepositoryMockRecorder) Connect(ctx, botToken, appToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockSlackRepository)(nil).Connect), ctx, botToken, appToken)
}

// Disconnect mocks base method.
func (m *MockSlackRepository) Disconnect() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Disconnect")
	ret0, _ := ret[0].(error)
	return ret0
}

// Disconnect indicates an expected call of Disconnect.
func (mr *MockSlackRepositoryMockRecorder) Disconnect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Disconnect", reflect.TypeOf((*MockSlackRepository)(nil).Disconnect))
}

// GetChannelMembers mocks base method.
func (m *MockSlackRepository) GetChannelMembers(ctx context.Context, channelID string) ([]user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChannelMembers", ctx, channelID)
	ret0, _ := ret[0].([]user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChannelMembers indicates an expected call of GetChannelMembers.
func (mr *MockSlackRepositoryMockRecorder) GetChannelMembers(ctx, channelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChannelMembers", reflect.TypeOf((*MockSlackRepository)(nil).GetChannelMembers), ctx, channelID)
}

// GetChannels mocks base method.
func (m *MockSlackRepository) GetChannels(ctx context.Context) ([]channel.Channel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChannels", ctx)
	ret0, _ := ret[0].([]channel.Channel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChannels indicates an expected call of GetChannels.
func (mr *MockSlackRepositoryMockRecorder) GetChannels(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChannels", reflect.TypeOf((*MockSlackRepository)(nil).GetChannels), ctx)
}

// GetMessages mocks base method.
func (m *MockSlackRepository) GetMessages(ctx context.Context, channelID string, limit int, cursor string) ([]message.Message, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessages", ctx, channelID, limit, cursor)
	ret0, _ := ret[0].([]message.Message)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetMessages indicates an expected call of GetMessages.
func (mr *MockSlackRepositoryMockRecorder) GetMessages(ctx, channelID, limit, cursor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessages", reflect.TypeOf((*MockSlackRepository)(nil).GetMessages), ctx, channelID, limit, cursor)
}

// GetThreadReplies mocks base method.
func (m *MockSlackRepository) GetThreadReplies(ctx context.Context, channelID, threadTS string) (message.Message, []message.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetThreadReplies", ctx, channelID, threadTS)
	ret0, _ := ret[0].(message.Message)
	ret1, _ := ret[1].([]message.Message)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetThreadReplies indicates an expected call of GetThreadReplies.
func (mr *MockSlackRepositoryMockRecorder) GetThreadReplies(ctx, channelID, threadTS any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetThreadReplies", reflect.TypeOf((*MockSlackRepository)(nil).GetThreadReplies), ctx, channelID, threadTS)
}

// PostMessage mocks base method.
func (m *MockSlackRepository) PostMessage(ctx context.Context, channelID, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostMessage", ctx, channelID, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// PostMessage indicates an expected call of PostMessage.
func (mr *MockSlackRepositoryMockRecorder) PostMessage(ctx, channelID, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostMessage", reflect.TypeOf((*MockSlackRepository)(nil).PostMessage), ctx, channelID, text)
}

// PostThreadReply mocks base method.
func (m *MockSlackRepository) PostThreadReply(ctx context.Context, channelID, threadTS, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostThreadReply", ctx, channelID, threadTS, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// PostThreadReply indicates an expected call of PostThreadReply.
func (mr *MockSlackRepositoryMockRecorder) PostThreadReply(ctx, channelID, threadTS, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostThreadReply", reflect.TypeOf((*MockSlackRepository)(nil).PostThreadReply), ctx, channelID, threadTS, text)
}

// SubscribeEvents mocks base method.
func (m *MockSlackRepository) SubscribeEvents(ctx context.Context) (<-chan port.SlackEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeEvents", ctx)
	ret0, _ := ret[0].(<-chan port.SlackEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeEvents indicates an expected call of SubscribeEvents.
func (mr *MockSlackRepositoryMockRecorder) SubscribeEvents(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeEvents", reflect.TypeOf((*MockSlackRepository)(nil).SubscribeEvents), ctx)
}
